<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Referencia al proyecto de la API para probar su capa de servicio -->
    <ProjectReference Include="..\ApiInnovacion.csproj" />
  </ItemGroup>

</Project>
